//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIDHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_61520_pidhubEntities : DbContext
    {
        public DB_61520_pidhubEntities()
            : base("name=DB_61520_pidhubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Battery> Batteries { get; set; }
        public virtual DbSet<ESC> ESCs { get; set; }
        public virtual DbSet<FlightControllerHardware> FlightControllerHardwares { get; set; }
        public virtual DbSet<FlightControllerSoftware> FlightControllerSoftwares { get; set; }
        public virtual DbSet<Frame> Frames { get; set; }
        public virtual DbSet<Motor> Motors { get; set; }
        public virtual DbSet<Prop> Props { get; set; }
        public virtual DbSet<Quad> Quads { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tune> Tunes { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
