//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIDHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quad
    {
        public Quad()
        {
            this.Tunes = new HashSet<Tune>();
        }
    
        public int Quad_ID { get; set; }
        public int User_ID { get; set; }
        public string QuadName { get; set; }
        public int FlightControllerHardwareID { get; set; }
        public int FlightControllerSoftwareID { get; set; }
        public int MotorID { get; set; }
        public int FrameID { get; set; }
        public int PropID { get; set; }
        public int ESCID { get; set; }
        public int BatteryID { get; set; }
    
        public virtual Battery Battery { get; set; }
        public virtual ESC ESC { get; set; }
        public virtual FlightControllerHardware FlightControllerHardware { get; set; }
        public virtual FlightControllerSoftware FlightControllerSoftware { get; set; }
        public virtual Frame Frame { get; set; }
        public virtual Motor Motor { get; set; }
        public virtual Prop Prop { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<Tune> Tunes { get; set; }
    }
}
