//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIDHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tune
    {
        public int Tune_ID { get; set; }
        public int Quad_ID { get; set; }
        public string TuneName { get; set; }
        public Nullable<decimal> Roll_P { get; set; }
        public Nullable<decimal> Pitch_P { get; set; }
        public Nullable<decimal> Yaw_P { get; set; }
        public Nullable<decimal> Roll_I { get; set; }
        public Nullable<decimal> Pitch_I { get; set; }
        public Nullable<decimal> Yaw_I { get; set; }
        public Nullable<decimal> Roll_D { get; set; }
        public Nullable<decimal> Pitch_D { get; set; }
        public Nullable<decimal> Yaw_D { get; set; }
        public Nullable<decimal> Roll_Rate { get; set; }
        public Nullable<decimal> Pitch_Rate { get; set; }
        public Nullable<decimal> Yaw_Rate { get; set; }
        public Nullable<decimal> Roll_RCRate { get; set; }
        public Nullable<decimal> Pitch_RCRate { get; set; }
        public Nullable<decimal> Yaw_RCRate { get; set; }
        public Nullable<decimal> Roll_RCCurve { get; set; }
        public Nullable<decimal> Pitch_RCCurve { get; set; }
        public Nullable<decimal> Yaw_RCCurve { get; set; }
        public Nullable<decimal> Roll_RCExpo { get; set; }
        public Nullable<decimal> Pitch_RCExpo { get; set; }
        public Nullable<decimal> Yaw_RCExpo { get; set; }
    
        public virtual Quad Quad { get; set; }
    }
}
